{ config, lib, pkgs, modulesPath, ... }:

{
  # ┌─────────────────────────────────────────────────────┐
  # │ This file is auto-generated by nixos-generate-config │
  # │ Run it on your actual hardware and replace this file │
  # └─────────────────────────────────────────────────────┘

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # These will be populated by nixos-generate-config
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystem mounts - update UUIDs after install
  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/REPLACE-ME";
  #   fsType = "ext4"; # or "btrfs"
  # };
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/REPLACE-ME";
  #   fsType = "vfat";
  # };

  hardware.cpu.amd.updateMicrocode = true;
}
