{ config, pkgs, ... }:

{
  networking.hostName = "xps13";

  # ── Intel GPU (Broadwell HD 5500) ───────────────────
  hardware.graphics.enable = true;

  boot.kernelParams = [
    "i915.enable_psr=0" # disable panel self-refresh (avoids flicker on older XPS)
  ];

  # ── Power management (laptop) ─────────────────────────
  services.thermald.enable = true;
  services.power-profiles-daemon.enable = true;

  # ── Bluetooth ─────────────────────────────────────────
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ── Lid/suspend behavior ──────────────────────────────
  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";
    HandleLidSwitchExternalPower = "lock";
  };

  # ── XPS 13 specific notes ─────────────────────────────
  # - No Docker on this machine (8GB RAM is too tight)
  # - Use this host for testing niri, theme, shell config
  # - hardware-configuration.nix generated by nixos-generate-config
  # - LUKS encryption optional on this test machine

  # ── Dell touchpad ─────────────────────────────────────
  services.libinput = {
    enable = true;
    touchpad = {
      naturalScrolling = true;
      tapping = true;
    };
  };
}
